### ISSUE TITLE
Enable the students to view the grades

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/github-flow-exercise#1]
**User story**:
As a student, calculating grades for each class is tedious. So, I want to see the grades online so that I don't have to do those calculations by hand.

* persona: student who does not want to calculate grades
* feature: student views the grades online
* business value: students do not have to waste professor's time to talk about grades

**Task List**

- [ ] Make sure the database schemes handle storing and viewing of grades
- [x] Create HTML view for viewing grades
- [ ] Connect the HTML views to the database/backend to finish the function

**Acceptance Criteria**
1. only for the current semester
2. works only for Chrome

**Acceptance Tests**
1. the student should be able to view existing grades for specific courses
2. the student should be able to view possible "what-if" grades for the course
